# Adding ACL entries: https://raymii.org/s/tutorials/Ansible_-_Only_if_a_file_exists_or_does_not_exist.html
# REQUIREMENTS
# pip install pan-python
# pip install pandevice
# pip install xmltodict
# ansible-galaxy install paloaltonetworks.paloaltonetworks
# https://www.bountysource.com/issues/59738537-certificate-verify-failed
#   set verify to disable in the virtual environment

---
- name: Convert Security Policy csv file to YAML variable file
  hosts: webserver
  gather_facts: False

  tasks:

    - name: Get acl_entries csv file from webserver
      fetch:
         src: "/home/{{ ansible_user }}/csvfiles/acl_entries_to_apply.csv"
         dest: "{{ playbook_dir }}/csvfiles/acl_entries_to_apply.csv"
         flat: yes


- name: Set up ACL entries
  hosts: ansible
  gather_facts: False
  become: yes
  vars:
    csvfile: "{{ lookup('file', '{{ playbook_dir }}/csvfiles/acl_entries_to_apply.csv') }}"

  vars_files:
    - ./vars/default_vars.yml

  tasks:
    - name: Check to see if acl_entries.yml exists
      stat:
        path: "{{ playbook_dir }}/vars/acl_entries.yml"
      register: acl_entries_output

    - name: Delete acl_entries.yml if it already exists
      file:
        path: "{{ playbook_dir }}/vars/acl_entries.yml"
        state: absent
      when: acl_entries_output.stat.exists == True

    - name: Create acl_entries.yml file from template
      template:
        src: "{{ playbook_dir }}/templates/acl_entries.j2"
        dest: "{{ playbook_dir }}/vars/acl_entries.yml"
